name: Compile site assets
on: push

jobs:
  compile:
    name: Compile assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run Docker container to compile assets
        uses: addnab/docker-run-action@v3
        with:
          image: aschmelyun/cleaver:latest
          options: -v ${{ github.workspace }}:/var/www
          run: |
            composer install
            npm install
            npm run production
            
  run-tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install --ignore-platform-req=ext-gd
      - name: Running phpunit
        run: ./vendor/bin/phpunit tests
